spring.application.name=emailmessage

spring.mail.host=smtp.gmail.com
spring.mail.username=khatiwadasandesh501@gmail.com
spring.mail.password=${APP_PASSWORD}
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true